---
apiVersion: v1
kind: Pod
metadata:
  name: csharp-memtest
  namespace: default
  labels:
    app: csharp-memtest
spec:
  containers:
  - name: csharp-memtest
    image: us-docker.pkg.dev/gke-demos-345619/gke-demos/csharp-memtest
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
    resources:
      requests:
        cpu: 1.0
        memory: 1G
      limits:
        cpu: 1.0
        memory: 1G